### PR TITLE
Feature/add description

### PR DESCRIPTION
**Pull request by phuongnq**
This PR is for issue https://github.com/craftercms/craftercms/issues/3588

### CODE REVIEW

**Review by avasquez614 — CHANGES_REQUESTED** [review]
In `Supported tags and respective Dockerfile links` for all images, put all the tags that don't end up in `BETA` and `SNAPSHOT`. The enterprise tags should be listed. Also there are som images that will not have all versions from 3.1.5

**Comment by phuongnq** [comment]
* Updated to use `E_BYOL` for enterprise images.
* Removed some images versions which are not available from 3.1.5
* For tags, I used tags listed here: https://github.com/craftercms/docker-images/tags

**Review by avasquez614 — CHANGES_REQUESTED** [review]
@phuongnq the `authoring_tomcat`, `delivery_tomcat`, `git_ssh_server`, `git_https_server` and `deployer also have enterprise images, so we're missing those.

**Comment by phuongnq** [comment]
@avasquez614 I updated to add enterprise images.

**Review by avasquez614 — APPROVED** [review]

**Pull request merged**
